### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by MrZhang3512** [open17/Bilibili_Downloader_Cli#1]
登录的时候报错：AttributeError: 'PyPNGImage' object has no attribute 'show'
 这个是什么问题

**Comment by open17** [comment]
看上去似乎是因为qrcode库的版本原因导致的登录二维码显示失败
查看一下qrcode版本是否低于2.4.2(在2.4.2中qrcode加入show)
尝试`pip install --upgrade "qrcode[pil]"`更新版本

**Comment by open17** [comment]
看起来是因为qrcode版本过旧或者未安装pillow导致的
你可以尝试`pip install -r requirements.txt` (新增了requirements.txt)
或者`pip install --upgrade "qrcode[pil]"`
